### ISSUE TITLE
LICENSE of the project unknown

### ISSUE THREAD

**Issue by doppelhelix** [marcinjahn/gnome-peek-top-bar-on-fullscreen-extension#2]
What is the LICENSE of the extension?

Thanks!

**Comment by marcinjahn** [comment]
Hi @doppelhelix. Given the straightforwardness of this solution, I didn't see the need to define a license. I doubt there's anything in this repository that could be construed as 'stealable'.

What is the context of your question? Do you want to reuse or fork the code? If so, I can add some free license for you to be able to do so without worry.

**Comment by doppelhelix** [comment]
Thanks!
It's always good to let others know who did all the work.
Now your extension is available on the [Arch User Repository (AUR)](https://aur.archlinux.org/packages/gnome-shell-extension-peek-top-bar-on-fullscreen-git).
