### ISSUE TITLE
After peeking, Neither hot-corner nor OS key works for toggling overview

### ISSUE THREAD

**Issue by bkurdali** [marcinjahn/gnome-peek-top-bar-on-fullscreen-extension#7]
This is happening on fedora 38, Gnome 44.2 on Wayland, I've attached a couple of screenshots.
You can see that the layout of the top bar has changed subtly as there is now a new invisible button on the far left where the hot-corner and activities button is. This sometimes 'fixes' itself, but I've no idea why. It only happens after I full screen an application and use the peek.
![before](https://github.com/marcinjahn/gnome-peek-top-bar-on-fullscreen-extension/assets/4793742/61ff2a48-a961-43fd-aee9-5da7f7b93fa0)
![after](https://github.com/marcinjahn/gnome-peek-top-bar-on-fullscreen-extension/assets/4793742/6354e1f3-ace8-46be-a1cb-5ef26977c57f)

**Comment by marcinjahn** [comment]
Hi @bkurdali. Unfortunately, this extension does not play well with Hot Corners enabled. I probably should add a remark about that to the README.md. I guess there is some possibility to keep hot corners working, but I didn’t have time to figure that out. 

The invisible button you see is a “trick” I used to get this extension to work in Wayland sessions. The panel would not appear at all unless some action on the panel is invoked. That’s why an artificial button is created and clicked on the panel when the panel shows up.

**Comment by tinkermakar** [comment]
isn't  this resolved with v8?

**Comment by marcinjahn** [comment]
Yeah, it seems that this issue got fixed by #9. Thanks @tinkermakar :slightly_smiling_face:
